import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const required=['index.html','package.json','vite.config.js','wrangler.toml','worker.js','Code.gs','src/main.jsx','src/styles.css','api/office-task.js','scripts/prebuild-check.mjs'];
for(const rel of required) if(!fs.existsSync(path.join(root,rel))) throw new Error(`Missing required file: ${rel}`);
const main=fs.readFileSync(path.join(root,'src/main.jsx'),'utf8');
const code=fs.readFileSync(path.join(root,'Code.gs'),'utf8');
const worker=fs.readFileSync(path.join(root,'worker.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const wrangler=fs.readFileSync(path.join(root,'wrangler.toml'),'utf8');
const vite=fs.readFileSync(path.join(root,'vite.config.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
if(/\b(?:if|for|while)\s*\([^\n)]*\)\s+(?:const|let|var)\b/.test(main)) throw new Error('Unsafe declaration in single-statement context detected in src/main.jsx.');
if(/import\s*\(\s*["']xlsx["']\s*\)/.test(main)) throw new Error('Dynamic XLSX import detected.');
const saveAttendanceBlock=(code.match(/function saveAttendance_\([\s\S]*?\n\}\n\nfunction punch_/)||[])[0]||'';
if(saveAttendanceBlock.includes('incoming[i-1]')&&!/const\s+incoming\s*=/.test(saveAttendanceBlock)) throw new Error('saveAttendance_ uses incoming breaks without declaring incoming.');
const declaredFns=new Set([...code.matchAll(/function\s+([A-Za-z0-9_$]+)\s*\(/g)].map(m=>m[1]));
const underscoreCalls=new Set([...code.matchAll(/\b([A-Za-z_$][A-Za-z0-9_$]*_)\s*\(/g)].map(m=>m[1]));
const undefinedHelpers=[...underscoreCalls].filter(name=>!declaredFns.has(name));
if(undefinedHelpers.length) throw new Error(`Undefined Apps Script helper/function reference(s): ${undefinedHelpers.join(', ')}`);
if(code.includes('break3NamazType')) throw new Error('Unexpected break3NamazType column regression detected.');
if(code.includes('3 Din Qafila')) throw new Error('Unexpected 3 Din Qafila task category regression detected.');
const frontend=[...main.matchAll(/api\(\s*["']([^"']+)["']/g)].map(m=>m[1]);
const backend=new Set([...code.matchAll(/case\s+["']([^"']+)["']/g)].map(m=>m[1]));
const missing=[...new Set(frontend)].filter(a=>!backend.has(a));
if(missing.length) throw new Error(`Frontend actions missing in Code.gs route_: ${missing.join(', ')}`);
if(!pkg.scripts?.build?.includes('vite build')) throw new Error('package.json build must run vite build.');
if(!pkg.scripts?.build?.includes('prebuild-check.mjs')) throw new Error('package.json build must run prebuild-check.mjs.');
if(!pkg.dependencies?.react||!pkg.dependencies?.['react-dom']||!pkg.devDependencies?.vite||!pkg.devDependencies?.['@vitejs/plugin-react']||!pkg.devDependencies?.wrangler) throw new Error('Required build dependencies are missing.');
if(!/main\s*=\s*["']worker\.js["']/.test(wrangler)) throw new Error('wrangler main must be worker.js.');
if(!/directory\s*=\s*["']\.\/dist["']/.test(wrangler)) throw new Error('wrangler assets directory must be ./dist.');
if(!/binding\s*=\s*["']ASSETS["']/.test(wrangler)) throw new Error('wrangler ASSETS binding missing.');
if(!/redirect:\s*["']follow["']/.test(worker)) throw new Error('Worker must follow Apps Script redirect.');
if(/redirect:\s*["']manual["']/.test(worker)) throw new Error('Manual redirect replay must not be used.');
if(!worker.includes('UPSTREAM_TIMEOUT_MS')) throw new Error('Worker timeout guard missing.');
if(!vite.includes('@vitejs/plugin-react')||!vite.includes('plugins: [react()]')) throw new Error('Vite React plugin configuration missing.');
if(!html.includes('/src/main.jsx')) throw new Error('index.html must load src/main.jsx.');
const apiProxy=fs.readFileSync(path.join(root,'api/office-task.js'),'utf8');
if(!/export\s+default\s+async\s+function\s+handler/.test(apiProxy)) throw new Error('api/office-task.js must use ESM export default because package.json uses type=module.');
if(/module\.exports\s*=/.test(apiProxy)) throw new Error('CommonJS module.exports is not allowed in api/office-task.js under type=module.');
if((code.match(/case\s+['"]setRamadanBreakFreeze['"]/g)||[]).length!==1) throw new Error('setRamadanBreakFreeze route must exist exactly once.');
if(!code.includes('function getEmployeeFileForDate_')) throw new Error('Date-aware employee file helper missing.');
if(!code.includes('function formatAttendanceDate_')) throw new Error('Attendance date formatter helper missing.');
if(!/function assignTask_[\s\S]*?getEmployeeFile_\(user,taskYear\)/.test(code)) throw new Error('assignTask_ must resolve the employee yearly file from the task date/year.');
if(!/if\(due<date\) throw new Error/.test(code)) throw new Error('assignTask_ must reject a To Date earlier than From Date.');
if(!code.includes('const existingEmail=')) throw new Error('Profile email preservation guard missing.');
if(!/V\.86/.test(code)||!/V\.86/.test(worker)||!/V\.86/.test(main)) throw new Error('V.86 version markers are inconsistent.');
if(/V\.(?:7[0-9]|8[0-4])/.test(code+'\n'+worker+'\n'+main)) throw new Error('Stale production version marker found in source.');
console.log(`Prebuild check passed: ${new Set(frontend).size} frontend API actions match Code.gs; Cloudflare, build, version and regression checks passed.`);
