import fs from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const required=['index.html','package.json','vite.config.js','wrangler.toml','worker.js','Code.gs','src/main.jsx','src/styles.css','api/office-task.js'];
for(const rel of required) if(!fs.existsSync(path.join(root,rel))) throw new Error(`Missing required file: ${rel}`);
const main=fs.readFileSync(path.join(root,'src/main.jsx'),'utf8');
const code=fs.readFileSync(path.join(root,'Code.gs'),'utf8');
const worker=fs.readFileSync(path.join(root,'worker.js'),'utf8');
const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
const wrangler=fs.readFileSync(path.join(root,'wrangler.toml'),'utf8');
if(/\b(?:if|for|while)\s*\([^\n)]*\)\s+(?:const|let|var)\b/.test(main)) throw new Error('Unsafe declaration in single-statement context detected in src/main.jsx.');
if(/import\s*\(\s*["']xlsx["']\s*\)/.test(main)) throw new Error('Dynamic XLSX import detected.');
if(code.includes('break3NamazType')) throw new Error('Unexpected break3NamazType column regression detected.');
if(code.includes('3 Din Qafila')) throw new Error('Unexpected 3 Din Qafila task category regression detected.');
const frontend=[...main.matchAll(/api\(\s*["']([^"']+)["']/g)].map(m=>m[1]);
const backend=new Set([...code.matchAll(/case\s+["']([^"']+)["']/g)].map(m=>m[1]));
const missing=[...new Set(frontend)].filter(a=>!backend.has(a));
if(missing.length) throw new Error(`Frontend actions missing in Code.gs route_: ${missing.join(', ')}`);
if(!pkg.scripts?.build?.includes('vite build')) throw new Error('package.json build must run vite build.');
if(!/main\s*=\s*["']worker\.js["']/.test(wrangler)) throw new Error('wrangler main must be worker.js.');
if(!/directory\s*=\s*["']\.\/dist["']/.test(wrangler)) throw new Error('wrangler assets directory must be ./dist.');
if(!/redirect:\s*["']follow["']/.test(worker)) throw new Error('Worker must follow Apps Script redirect.');
if(/redirect:\s*["']manual["']/.test(worker)) throw new Error('Manual redirect replay must not be used.');
if(!worker.includes('UPSTREAM_TIMEOUT_MS')) throw new Error('Worker timeout guard missing.');
console.log(`Prebuild check passed: ${new Set(frontend).size} frontend API actions match Code.gs; proxy/build regression checks passed.`);
